### ISSUE TITLE
Robots not working with new docker images

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#378] opened 2020-04-07 06:35 UTC
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/378)) by Malcolm Stagg (Bitbucket: [malcolmst7](https://bitbucket.org/%7Beee13832-fdd5-4196-aa05-6cfdb1118c65%7D/)).**

----------------------------------------
As far as I can tell, everything seems to be working fine locally using docker-compose, but in cloudsim \(and also in an AWS environment I’m currently setting up\) the robots are not able to move correctly. Data seems to be getting lost, and I am seeing the following error message in my logs:

```
458.268000000 WARN /X2N1/detect_ros [tcpros_base.py:352(TCPROSServer._tcp_server_callback)] [topics: /clock, /X2N1/front/image_raw, /X2N1/objects, /rosout, /X2N1/debug_image, /statistics] Inbound TCP/IP connection failed: timed out
458.268000000 WARN /X2N1/hazard_detector [tcpros_base.py:352(TCPROSServer._tcp_server_callback)] [topics: /clock, /X2N1/front/image_raw, /rosout, /X2N1/hazard, /statistics] Inbound TCP/IP connection failed: out timed
```

\(Note that both of those lines are from Python modules\)

In the `rostopic_247_1586233084153.log` file I see the following:

```
[rospy.internal][INFO] 2020-04-06 21:27:47,640: topic[/statistics] adding connection to [http://10.40.0.4:36633/], count 13
[rospy.internal][WARNING] 2020-04-06 22:20:10,011: Unknown error initiating TCP/IP socket to 10.40.0.4:45261 (http://10.40.0.4:39845/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-04-06 22:20:10,014: topic[/statistics] removing connection to http://10.40.0.4:39845/
```

This behavior actually looks similar to the #339 issue, and I am seeing some of the same messages in my logs as when that was occurring.

That log is from CloudSim guid `a71032a3-5aca-452e-b2a0-aaae898ca272` which is an example of this behavior.

**Comment by malcolmst** [comment] 2020-04-09 18:34
Updating with messages that didn't get migrated:

**Comment by malcolmst** [comment] 2020-04-09 18:34
Just as an update, I am running this now on AWS with two robots. On one robot I see no sign of a memory leak, and on the other, `move_base` is steadily increasing its memory usage. Both robots are stopped and not moving correctly. This is with the 04/06 sim & bridge images. If I go back to the 03/29 images, everything is working fine. I’ll keep on investigating as much as I can on my end.

**Comment by malcolmst** [comment] 2020-04-09 18:35
Just tried the 03/29 bridge image with the 04/06 sim image, and that is also working fine. Seems like this is somehow related to the new topic logging updates in the bridge container.

**Comment by malcolmst** [comment] 2020-04-09 18:35
One more quick update, the reason why I wasn’t getting a repro on my local computer turned out to be because I was using a slightly newer version of my solution docker container with docker-compose. When I switch to the same older version of my solution container, along with the 04/06 bridge container, I can reproduce this issue locally. However, I don’t see any changes in my solution which should have an impact on this. They do use different versions of the base `osrf/subt-virtual-testbed` image though, which could be related. Will investigate some more.

**Comment by malcolmst** [comment] 2020-04-09 18:35
One more update... if I run `apt-get upgrade` on the docker container that has this problem, it magically fixes it and then it works fine with the 04/06 images. Now to figure out which package is causing the problem....

**Comment by malcolmst** [comment] 2020-04-09 18:35
Found the package! (with a binary search): if I upgrade `ros-melodic-roscpp` to the newest version in my solution container, this problem is resolved.

The old version where I see this bug is `1.14.3-0bionic.20191210.230336` and the new version is `1.14.5-1bionic.20200320.102657`.

**Comment by malcolmst** [comment] 2020-04-09 18:36
I did another bisect and found where this changed: https://github.com/ros/ros_comm/commit/943f37382809da20170b6b4715f46c1a13363c97

It looks like before this change, many *fewer* messages were being published to `/statistics` than should have been. Not sure why is was causing my robots to have this behavior though, or if this could be at all related to what was happening in #339 (which had very similar symptoms).

**Comment by malcolmst** [comment] 2020-04-17 14:55
To summarize this issue (sorry for all the posts), it seems competitor images from before 02/2020 may not work correctly with the newly enabled topic logging due to a roscpp bug which was fixed in https://github.com/ros/ros_comm/commit/943f37382809da20170b6b4715f46c1a13363c97 but not released until last month. Not sure exactly what the interaction is, might be a memory leak in the statistics aggregation for frequently published topics. The statistics isn’t published due to that bug, so the buffer keeping track of message rates, etc continues to grow. 

I guess there’s nothing to fix here since the roscpp bug was already fixed, but it’s just something to keep in mind that pre-February 2020 containers might not behave correctly unless they are using a custom roscpp build.

**Comment by malcolmst** [comment] 2020-04-28 21:48
Update: I started running things in CloudSim again, and when using a current version, I no longer hit this issue locally, but I do seem to be hitting this in CloudSim. I see the same memory leak and error messages, so it seems likely it is the same problem related to topic logging. 

But no idea why I wouldn’t be hitting it locally or in my own simulation environment when all the versions of everything are the same.

**Comment by nkoenig** [comment] 2020-04-29 17:18
Do you have a cloudsim groupid that I should look at?

**Comment by nkoenig** [comment] 2020-04-29 18:13
I looked at logs from `54e01a39-e78e-4299-9c03-cd8d2527a511` by running `atop -r atop_log`. I observed the memory leak, but I noticed that the leak occurred outside the bridge container. You can see this my pressing the `m` key during atop playback. Notice that none of the recorded processes leak memory, but the overall free system memory drops.

The atop logger runs inside the bridge container, and can only record process information that are local to the bridge. It can however see overall system memory and cpu usage. 

Do you think topic statistics logging in the bridge is causing a memory leak in the solution container?

**Comment by malcolmst** [comment] 2020-04-29 23:51
Thank you, Nate, for taking another look at this. That lines up with what I have been seeing too. When I was seeing this earlier and could reproduce it locally (due to the older `roscpp` library) I could see it was `move_base` in my solution container which was leaking the memory.

I'm not sure exactly how that would be happening now, but suspect if it is related to the topic statistics logging, probably the logging is causing an extra delay in the topic callbacks, which is somehow causing a chain reaction resulting in the memory leak and failures. I will do my best to investigate that further on my end, since I want to make sure my solution container is able to tolerate reasonable delays anyway.

Interestingly, I did a couple runs last night which did not hit this issue (ab1b1eeb-9d0a-45fd-852e-5b6ac3cdc6d0 and 12a8d50e-83c2-4654-b58a-d5c24ad0f6a8). I think the only difference between those and the earlier run you were looking at, besides some unrelated improvements, was that I was running two robots instead of just one.

**Comment by nkoenig** [comment] 2020-08-17 17:14
Closing this issue in order to triage the issue tracker.

**Closed by nkoenig** 2020-08-17 17:14 UTC
Labels: bug, minor
