### ISSUE TITLE
Problems with Cloudsim

### ISSUE THREAD

**Issue by osrf-migration** [osrf/subt#339] opened 2020-01-30 11:30 UTC
**Original report ([archived issue](https://osrf-migration.github.io/subt-gh-pages/#!/osrf/subt/issues/339)) by Sophisticated Engineering (Bitbucket: [sopheng](https://bitbucket.org/%7B12ed2357-e253-4c67-a2b9-7e12c64773e4%7D/)).**

----------------------------------------
We have problems with cloudsim on the portal.

Tests from last night are running very long and have the Status “Deleting Pods”. And some have additionally “Error: Admin Review”.

I’ve send an Email to subt-help.

Is this problem also seen by other teams?

**Comment by malcolmst** [comment] 2020-04-21 09:05
@bfotheri FYI, I'm fairly sure I finally did discover the root cause of this issue last week and shared it with the SubT team.

CloudSim uses WeaveNet to provide networking and network isolation to the containers. This works as expected for unicast packets, but WeaveNet NPC has some counter-intuitive behavior that it does not block multicast packets from being sent to all hosts (even other competitors), as detailed in this issue: https://github.com/weaveworks/weave/issues/3272. Ignition Transport uses multicast UDP packets for topic advertisements among other things, so all topic advertisements for any running robot were unexpectedly being sent to all hosts, where most of the topics would get filtered out on the receiving end. I was able to confirm this was the case by running two simulations simultaneously and logging all the topics before they were filtered out, and I found the isolation between those two simulations was indeed broken.

I also wrote some test code: https://github.com/sodium24/cloudsim_net_test which confirmed that when enough topic advertisements are received (on the order of several thousand), even though most are eventually filtered out, the infrastructure containers stop working correctly, and topic data, especially `tf` data, begins to become lost. This can be seen in the `ign_saturation` test cases. I was able to reproduce the issue of my robots either not moving or spinning in circles outside the entrance on my local computer. Anyone feel free to use/update this test code btw. There are also some test cases there which might be helpful to ensure things are working alright despite some common network impairments. 

Based on this strong evidence, I believe the Urban Circuit issues were caused by the excessive rate of multicast Ignition Transport packets unexpectedly being delivered to all hosts, resulting from the WeaveNet issue combined with the large number of simulations and robots running at the same time. 

The SubT team let me know that they are investigating this on their end. I haven't heard any update since then, but I see from the CloudSim Web repo that an update was made last week which will allow multicast to be disabled and replaced with unicast, which should fix this issue, so I expect we'll hear some update before too long.

**Comment by zwn** [comment] 2020-04-21 13:24
@malcolmst Kudos. 

Now we only need to know which version is running on cloudsim which is actually impossible for us to find out :worried:. I very doubt it is the release announced today since the PR it links to is not merged yet. However, the images at https://hub.docker.com/r/osrf/subt-virtual-testbed/tags seem to have been updated recently. Too bad that #377 is not addressed yet, or even better #256. Or maybe #193 anyone?

**Comment by bfotheri** [comment] 2020-04-21 14:41
@malcolmst an additional Kudos. Thank you for your investigation. You absolutely nailed it. I feel like there are a number of workaround/fixes but we'll see what OSRF says. Thanks again!!

**Comment by angelacmaio** [comment] 2020-04-22 00:32
@malcolmst Thank you for the investigation. We are now blocking multicast and using IGN_RELAY with [this PR](https://gitlab.com/ignitionrobotics/web/cloudsim/-/merge_requests/20). Ignition Transport topic advertisements will no longer be available to all instances. This fix has been deployed to Cloudsim.

The bridge can be stressed by simultaneous advertisement of many Ignition Transport topics. ~10K topic advertisements is an order of magnitude larger than what occurs on Cloudsim even during the largest usage spikes.

With your test case, we can reproduce the circling robots but have not seen indications of data loss (as recorded by the new bridge logger). Note that the `subt_seed` solution contains a blocking service call that is affected by stress on Ignition Transport, but the solution may be altered to respond well despite longer service calls (see the fix [here](https://github.com/osrf/subt_seed/pull/2)).  We are also testing [this PR](https://github.com/osrf/subt/pull/402) to reduce topic bandwidth, which may improve the timing consistency.

We are continuing to stress test the infrastructure and the sample `subt_hello_world` solution and hope to have additional recommendations soon.

**Comment by malcolmst** [comment] 2020-04-23 02:40
Thanks @zwn and @bfotheri, appreciate it! It sure wasn't obvious to find, I searched everything else I could think of for possible network issues, etc, then finally just found it hiding there in plain sight. 
And thank you for your update, @angelacmaio, glad to hear the `IGN_RELAY` fix has been deployed.

**Comment by nkoenig** [comment] 2020-08-11 14:33
Cloudsim has seen many improvements. I'm closing this issue in order to triage the issue tracker. Please create a new issue if you see more problems with Cloudsim.

**Closed by nkoenig** 2020-08-11 14:33 UTC
Labels: major, task
