### ISSUE TITLE
DNS issue with www.subtchallenge.com

### ISSUE THREAD

**Issue by malcolmst** [osrf/subt#676] opened 2020-10-17 07:49 UTC
I thought this might have been just a temporary glitch, but I've noticed for quite a while (weeks, maybe months) that computers on my network cannot resolve www.subtchallenge.com using a default DNS configuration (my ISP is Spectrum). If I add `8.8.8.8` as a DNS server though, it resolves fine. On my phone, www.subtchallenge.com resolves fine on 4G but not wifi on my network. I can try to get more details about the default DNS configuration if it would be helpful.

I expect this is some issue with my ISP, but wanted to let you know in case it's more widespread than just me.

Before adding `8.8.8.8`:

```
nslookup www.subtchallenge.com
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find www.subtchallenge.com: SERVFAIL
```

After:
```
nslookup www.subtchallenge.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	www.subtchallenge.com
Address: 192.5.18.235
```

[update] This appears to also affect the `1.1.1.1` and `1.0.0.1` DNS servers:

```
nslookup
> server 8.8.8.8
Default server: 8.8.8.8
Address: 8.8.8.8#53
> www.subtchallenge.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	www.subtchallenge.com
Address: 192.5.18.235
> server 1.1.1.1
Default server: 1.1.1.1
Address: 1.1.1.1#53
> www.subtchallenge.com
Server:		1.1.1.1
Address:	1.1.1.1#53

** server can't find www.subtchallenge.com: SERVFAIL
> server 1.0.0.1
Default server: 1.0.0.1
Address: 1.0.0.1#53
> www.subtchallenge.com
Server:		1.0.0.1
Address:	1.0.0.1#53

** server can't find www.subtchallenge.com: SERVFAIL
```

**Comment by malcolmst** [comment] 2020-10-17 07:50
Also, this is just www.subtchallenge.com, www.subtchallenge.world works fine.

**Comment by zwn** [comment] 2020-10-19 12:22
I am also using the cloudflare dns resolvers and it fails for me as well. I've created a ticket there just in case the problem is on cloudflare side: https://community.cloudflare.com/t/subtchallenge-com-not-resolving/214948

**Comment by angelacmaio** [comment] 2020-10-19 16:10
This information has been routed to the proper group. Since subtchallenge.com is not part of the SubT Virtual Testbed, I will close this issue. If you have any further information, please send to SubTChallenge@darpa.mil.

**Closed by angelacmaio** 2020-10-19 16:10 UTC
