### ISSUE TITLE
Camera rendering issues in cave practice 01

### ISSUE THREAD

**Issue by malcolmst** [osrf/subt#653] opened 2020-10-07 08:22 UTC
I haven't been looking at much of the raw camera data lately with the cave practice worlds, but just took a close look at some bag data gathered from `980f509e-4ab2-4170-9675-485ae7ea2d27` (cave practice 01). I'm seeing some really weird rendering and lighting/shadow issues, especially near the entrance, but also going into the cave as well. This is just taken from the compressed camera topics.

The following is camera data from an X2 robot entering the cave:

![x2n1_lighting_issues_start1](https://user-images.githubusercontent.com/23696107/95304511-57e29000-084a-11eb-8765-4711609473d1.gif)

And another X2 robot waiting outside the entrance, then entering:

![x2n2_lighting_issues_start1](https://user-images.githubusercontent.com/23696107/95304958-fa027800-084a-11eb-9ff5-d5e827328779.gif)

Then some strange lighting effects inside the cave near the first rope artifact:

![x2n2_lighting_issues_inside_cave](https://user-images.githubusercontent.com/23696107/95305657-e6a3dc80-084b-11eb-9009-3d2d03d077d5.gif)

I'll keep a lookout for any similar effects in the other worlds.

**Comment by malcolmst** [comment] 2020-10-07 08:34
The super-brightness seems to come and go really quickly depending on the angle to a nearby obstacle:

![x2n2_lighting_issues2](https://user-images.githubusercontent.com/23696107/95307083-d3920c00-084d-11eb-90dd-231f71619fa2.gif)

**Comment by nkoenig** [comment] 2020-10-07 14:00
I believe this is a duplicate of issue #635

**Comment by malcolmst** [comment] 2020-10-07 19:36
Yes I think you’re right, sorry I missed that

**Comment by nkoenig** [comment] 2020-10-08 00:36
Duplicate of #635.

**Closed by nkoenig** 2020-10-08 00:36 UTC
Labels: duplicate
