### ISSUE TITLE
Camera Rendering Broken on AWS

### ISSUE THREAD

**Issue by rsawtell** [osrf/subt#635] opened 2020-09-29 13:43 UTC
Images we bagged from our latest run reveal some sort of camera simulation failure on the AWS, namely that all or part of the world appears to disappear from the perspective of the camera system leaving a mostly black screen in which only certain things (artifacts and other robots) appear to be rendered. The failure seems intermittent, but affected every robot at some point.

Valid image taken by a UAV, and a corrupted image a few seconds later:
![Xd_sidebyside](https://user-images.githubusercontent.com/700223/94563721-15f78f80-0235-11eb-9ab0-0f5a2e41065d.jpg)

Same UAV later in the simulation, part of the world is visible while other parts are not:
![Xe_2020273090909041170](https://user-images.githubusercontent.com/700223/94564782-63c0c780-0236-11eb-9b5a-77f96ede5685.png)

View of a rescue randy by a UGV, note the shadowed area at the bottom should be obscured by terrain (you may have to adjust your contrast but you can see the entire rescue randy, it's just darker):
![Xb_xray](https://user-images.githubusercontent.com/700223/94563904-58b96780-0235-11eb-897e-6b96acd9fb3b.jpg)

Not sure if this is related or not, but the log playback seems mostly fine except depending on the perspective you get things like this (the camera is not inside any geometry):
![image](https://user-images.githubusercontent.com/700223/94564363-e5fcbc00-0235-11eb-90d4-e737ae06e1c4.png)

or as a GIF:
![PlaybackWeirdness](https://user-images.githubusercontent.com/700223/94565654-7d164380-0237-11eb-8376-3d2e5909cb06.gif)

For reference the simulation id is 165fd66a-ab7f-471e-91b7-a49cf616f129

**Comment by nkoenig** [comment] 2020-09-29 18:18
Thanks. I'm looking into it.

**Comment by iche033** [comment] 2020-09-29 18:38
@rsawtell, are the images from an rgbd camera? Do you know the approximate locations in the world where the UAV captured these images?

**Comment by rsawtell** [comment] 2020-09-29 19:25
These are from HD camera configurations. The locations appear to be almost anywhere in the tunnel, it's not really limited to specific locations. In the above examples they are the helmet to the right after entering the tunnel, the starting area, and the first rescue randy on the left branch of the tunnel. Probably 90% of the images I captured had the problem though from basically anywhere the robots visited, and this seems new to this run as I've been capturing images for awhile now. I also don't see it in local development testing, though i haven't tried cloudsim.

**Comment by peci1** [comment] 2020-09-30 09:22
Just to make sure - do you use an english locale in your system? Try running the GUI with environment `LC_ALL=C LANG=C`.

**Comment by rsawtell** [comment] 2020-09-30 15:04
We are running on an english locale.

We also saw this problem on our latest run: 
Run ID: b964c8b7-b8a5-42c1-9f31-b1368ed2be60

![Xh_2020274110119642831](https://user-images.githubusercontent.com/700223/94703209-9c32d500-030c-11eb-8d05-e97c5c586aef.png)

**Comment by nkoenig** [comment] 2020-10-01 22:05
The issue is caused by surpassing a shadow caster limit in Ogre2. A patch is in progress. I the mean time you have a couple options:

1. Run with fewer robots. I realize this is not a long term solution.
2. Turn off shadow casting on some of the lights on your robots. This solution will only affect local runs. Look for the `<cast_shadows>` tag in the `model.sdf` file.

I'll update this issue when the patch is in place.

**Comment by rsawtell** [comment] 2020-10-02 14:47
Thanks for the update, we'll keep this in mind.

**Comment by malcolmst** [comment] 2020-10-07 22:39
For robot budgeting purposes, is it safe to assume this will be fixed before cave circuit?

**Comment by nkoenig** [comment] 2020-10-08 00:39
Fix has been on Cloudsim, public dockerhub images are uploading. Release notes are here: https://github.com/osrf/subt/wiki/release_notes#2020-10-07,

**Closed by nkoenig** 2020-10-08 00:39 UTC

**Comment by malcolmst** [comment] 2020-10-08 00:56
Awesome! Thanks for the update.
