### ISSUE TITLE
Incomplete model closure in start area

### ISSUE THREAD

**Issue by rsawtell** [osrf/subt#408] opened 2020-04-22 17:41 UTC
One of the boundary rocks in the start area doesn't fully reach to the ground, our robot found it and drove into it, getting lodged partly inside a rock.

I apologize for the cruddy pictures but the simulator window is very dark.

Approximate location of the problem (circled in red):
![image](https://user-images.githubusercontent.com/700223/80014648-9358f000-849e-11ea-879b-66e04e4a6766.png)

Visual of the problem area:
![image](https://user-images.githubusercontent.com/700223/80014839-e2068a00-849e-11ea-87be-5888e24f8307.png)

Poor X2 stuck halfway inside a rock, it was only trying to escape the labrynth so it could be free :
![image](https://user-images.githubusercontent.com/700223/80014764-c307f800-849e-11ea-8011-c4a40b305e41.png)

**Comment by nkoenig** [comment] 2020-04-22 21:37
Thanks for point this out. We are working on a fix.

**Comment by iche033** [comment] 2020-04-23 21:01
uploaded new `Cave Starting Area` model onto fuel:
https://app.ignitionrobotics.org/openrobotics/fuel/models/Cave%20Starting%20Area

**Comment by rsawtell** [comment] 2020-04-30 20:16
Not sure if it's related, but I am also seeing these errors running local:

[GUI] [Err] [Material.cc:155] Unable to find texture[../media/textures/CaveWall_Albedo.png] in path[###/.ignition/fuel/fuel.ignitionrobotics.org/openrobotics/models/Cave Starting Area/3//meshes]
[GUI] [Err] [Material.cc:155] Unable to find texture[../media/textures/Grass_Albedo.jpg] in path[###/.ignition/fuel/fuel.ignitionrobotics.org/openrobotics/models/Cave Starting Area/3//meshes]
[GUI] [Err] [Material.cc:155] Unable to find texture[../media/textures/StriatedRock_Albedo.png] in path[###/.ignition/fuel/fuel.ignitionrobotics.org/openrobotics/models/Cave Starting Area/3//meshes]

**Comment by nkoenig** [comment] 2020-05-01 14:05
That  image looks like the user camera's clipping plane has interested the mesh, and clipped part of the tunnel. Can you reproduce that using a camera on a robot?

**Comment by rsawtell** [comment] 2020-05-01 14:21
Yes, here it is from an X1. Notice that the hole shows up in the lidar scan as well.

![image](https://user-images.githubusercontent.com/700223/80812142-58894300-8b95-11ea-911c-56e89b32aa8e.png)

**Comment by iche033** [comment] 2020-05-04 21:58
the gap in the cave entrance area should now be fixed too. Model on fuel has been updated:
https://app.ignitionrobotics.org/openrobotics/fuel/models/Cave%20Starting%20Area

**Comment by nkoenig** [comment] 2020-05-07 12:24
New docker images with the patches have been released. I'll close this for now. Please re-open if more holes in the staging area are found.

**Closed by nkoenig** 2020-05-07 12:24 UTC
